[package]
name = "pow-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
indicatif = "0.17"
ccb = "0.1.1"